name: Dependabot Pull Request Triage

on:
  pull_request:
    types:
      - opened

jobs:
  triage:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Assign Reviewer
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor}} # assign pull request author
          reviewers: dalhougaard # if draft, assigned when draft is released