name: Dependabot Pull Request Triage

on:
  pull_request:
    types:
      - opened

jobs:
  triage:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Add Labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'dependabot, security'

      - name: Assign Reviewer
        uses: hkusu/review-assign-action@v1
        with:
          assignees: dalhougaard # assign pull request author
          reviewers: dalhougaard # if draft, assigned when draft is released