name: Dependabot Pull Request Triage

on:
  pull_request:
    types:
      - opened

jobs:
  triage:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Auto Request Review
        uses: necojackarc/auto-request-review@v0.13.0
        with:
          reviewers:
            defaults:
              - repository-owners